### ISSUE TITLE
Broken Child Editor

### ISSUE THREAD

**Issue by brittany89** [Atwix/package-PVF#4]
![screenshot](https://cloud.githubusercontent.com/assets/9436089/4813649/5725caf4-5eca-11e4-8d05-7d7ddb8fdd51.jpg)

We are getting this fetal error: Call to a member function setBeforeHtml() on a non-object in /home/mx/public_html/app/code/community/Atwix/PVF/Model/Observer.php on line 14. When we click to edit a simple product within the configurable product

**Comment by rogyar** [comment]
Hello brittany89, 
Tell us about your Magento version please.

**Comment by brittany89** [comment]
We have version 1.9.0

**Comment by yaro-atwix** [comment]
Appreciate for your report. We have fixed the issue. Please, try the latest version and let us know if the issue on your side is fixed. 
Thanks.

**Comment by brittany89** [comment]
Works great!! Thank you so much. This is an amazing extension.
